const config={
    //服务器端口
    port:3001,
    //数据库配置
    database:{
        DATABASE:'mall_front_end',
        USERNAME:'root',
        PASSWORD:'FSG851024125',
        PORT:'3306',
        HOST:'localhost'
    },
    //状态码配置
    codeOption:{
        success:'1',
        fail:'0',
        tokenInvalid:'1000'
    }
}
module.exports=config